// <auto-generated />
using System;
using LifeSystem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeSystem.Api.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260721104547_Fase4Mentor")]
    partial class Fase4Mentor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("LifeSystem.Api.Domain.Amizade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConvidadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SolicitanteId", "ConvidadoId")
                        .IsUnique();

                    b.ToTable("Amizades");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.AporteEconomia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId", "Data");

                    b.ToTable("Aportes");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.ChefeInstancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChefeIndice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enfurecido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HpAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HpMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("SemanaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId", "SemanaInicio")
                        .IsUnique();

                    b.ToTable("ChefesInstancias");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.ConquistaDesbloqueada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConquistaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DesbloqueadaEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId", "ConquistaId")
                        .IsUnique();

                    b.ToTable("ConquistasDesbloqueadas");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.ConselhoMentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId", "Data");

                    b.ToTable("ConselhosMentor");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.Divida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<double>("JurosPctMes")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("QuitadaEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId");

                    b.ToTable("Dividas");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.Habilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrilhaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.InteracaoSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId", "Data")
                        .IsUnique();

                    b.ToTable("InteracoesSociais");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.ItemLoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Preco")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId");

                    b.ToTable("ItensLoja");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HabilidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.MarcoConcluido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarcoIndice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadeId", "MarcoIndice")
                        .IsUnique();

                    b.ToTable("MarcosConcluidos");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.MissaoLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChecksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissaoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressoMinutos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId", "MissaoId", "Data")
                        .IsUnique();

                    b.ToTable("MissoesLog");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.PerfilCorporal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlturaCm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Atividade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PesoKg")
                        .HasColumnType("REAL");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId")
                        .IsUnique();

                    b.ToTable("PerfisCorporais");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.PerfilFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DespesasFixas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DespesasVariaveis")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrcamentoRecompensa")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RendaMensal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId")
                        .IsUnique();

                    b.ToTable("PerfisFinanceiros");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvatarTranscendente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AvisoFinancasAceitoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AvisoSaudeAceitoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChefesDerrotados")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClasseEscolhidaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoAmigo")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasPerfeitos")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Economias")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Moedas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtecoesStreak")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RankingOptIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecompensaCaixa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StreakDias")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TranscendenciaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("UltimoDiaComMissao")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpAtual")
                        .HasColumnType("INTEGER");

                    b.Property<long>("XpTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAmigo")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.RegistroCardio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("REAL");

                    b.Property<double>("DuracaoMin")
                        .HasColumnType("REAL");

                    b.Property<int?>("FaixaKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaceSegKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrPremiado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId", "Data");

                    b.ToTable("RegistrosCardio");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.RegistroCarga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CargaKg")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExercicioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrPremiado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rm1")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId", "ExercicioId", "Data");

                    b.ToTable("RegistrosCarga");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.SessaoFoco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EncerradaEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HabilidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IniciadaEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId");

                    b.ToTable("SessoesFoco");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.TransacaoMoedas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId");

                    b.ToTable("TransacoesMoedas");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.ChefeInstancia", b =>
                {
                    b.HasOne("LifeSystem.Api.Domain.Personagem", null)
                        .WithMany("Chefes")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.ConquistaDesbloqueada", b =>
                {
                    b.HasOne("LifeSystem.Api.Domain.Personagem", null)
                        .WithMany("Conquistas")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.ItemLoja", b =>
                {
                    b.HasOne("LifeSystem.Api.Domain.Personagem", null)
                        .WithMany("Loja")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.MarcoConcluido", b =>
                {
                    b.HasOne("LifeSystem.Api.Domain.Habilidade", null)
                        .WithMany("Marcos")
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.MissaoLog", b =>
                {
                    b.HasOne("LifeSystem.Api.Domain.Personagem", null)
                        .WithMany("Missoes")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.PerfilCorporal", b =>
                {
                    b.HasOne("LifeSystem.Api.Domain.Personagem", null)
                        .WithOne("PerfilCorporal")
                        .HasForeignKey("LifeSystem.Api.Domain.PerfilCorporal", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.PerfilFinanceiro", b =>
                {
                    b.HasOne("LifeSystem.Api.Domain.Personagem", null)
                        .WithOne("PerfilFinanceiro")
                        .HasForeignKey("LifeSystem.Api.Domain.PerfilFinanceiro", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.Personagem", b =>
                {
                    b.HasOne("LifeSystem.Api.Domain.Usuario", null)
                        .WithOne("Personagem")
                        .HasForeignKey("LifeSystem.Api.Domain.Personagem", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.SessaoFoco", b =>
                {
                    b.HasOne("LifeSystem.Api.Domain.Personagem", null)
                        .WithMany("SessoesFoco")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.TransacaoMoedas", b =>
                {
                    b.HasOne("LifeSystem.Api.Domain.Personagem", null)
                        .WithMany("Transacoes")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.Habilidade", b =>
                {
                    b.Navigation("Marcos");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.Personagem", b =>
                {
                    b.Navigation("Chefes");

                    b.Navigation("Conquistas");

                    b.Navigation("Loja");

                    b.Navigation("Missoes");

                    b.Navigation("PerfilCorporal");

                    b.Navigation("PerfilFinanceiro");

                    b.Navigation("SessoesFoco");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("LifeSystem.Api.Domain.Usuario", b =>
                {
                    b.Navigation("Personagem")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
